---
abstract: 'simple InteractiveBrokers API (blocking abstraction over AnyEvent::TWS)'
author:
  - 'Uwe Voelker <uwe@uwevoelker.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300026, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-TWS-Simple
version: 0.000_01
